// This file was generated by github.com/nelsam/hel.  Do not
// edit this code by hand unless you *really* know what you're
// doing.  Expect any changes made manually to be overwritten
// the next time hel regenerates this file.

package connectionmanager_test

type mockAppIDStore struct {
	AddCalled chan bool
	AddInput  struct {
		AppID chan string
	}
	GetCalled chan bool
	GetOutput struct {
		Ret0 chan string
	}
}

func newMockAppIDStore() *mockAppIDStore {
	m := &mockAppIDStore{}
	m.AddCalled = make(chan bool, 100)
	m.AddInput.AppID = make(chan string, 100)
	m.GetCalled = make(chan bool, 100)
	m.GetOutput.Ret0 = make(chan string, 100)
	return m
}
func (m *mockAppIDStore) Add(appID string) {
	m.AddCalled <- true
	m.AddInput.AppID <- appID
}
func (m *mockAppIDStore) Get() string {
	m.GetCalled <- true
	return <-m.GetOutput.Ret0
}
